import type { Metadata } from "next";
import Image from "next/image";
import localFont from "next/font/local";
import Header from "../components/layout/header/Header";
import "./globals.css";

const vcrOsdMono = localFont({
  src: [
    { path: '../../public/fonts/VCR_OSD_MONO_1.001.ttf', weight: '400', style: 'normal' },
  ],
  variable: '--font-vcr-osd-mono',
});

const departuremono = localFont({
  src: [
    { path: '../../public/fonts/DepartureMono.otf', weight: '400', style: 'normal' },
  ],
  variable: '--font-departure-mono',
});

const ivyPresto = localFont({
  src: [
    { path: '../../public/fonts/IvyPresto.woff2' },
  ],
  variable: '--font-ivy-presto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${vcrOsdMono.variable} ${departuremono.variable} ${ivyPresto.variable}`}>
      <body>
        <Header/>
        <Image 
          src="/eyes.gif" 
          alt="Loading animation" 
          width={300} 
          height={210} 
        />
        {children}
      </body>
    </html>
  );
}
